try{
    console.log(x);
}catch(error){

    console.log('Error :' + error);
}